name: update-year

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every half hour
    - cron:  '0,30 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: find the date and publish it
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "automation@github.com"
          git config user.name "github automation"
          ./publish
